include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    library_private_types_in_public_api: ignore
    file_names: ignore
    avoid_print: ignore
    dead_code: ignore
    prefer_const_constructors: ignore
